
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have ingot melting recipes added.
	materialToMoltenMaterialBlacklist = []
	#The materials that should not have nugget melting recipes added.
	nuggetToMoltenMaterialBlacklist = []
	#The materials that should not have dust melting recipes added.
	dustToMoltenMaterialBlacklist = []
	#The materials that should not have plate melting recipes added.
	plateToMoltenMaterialBlacklist = []
	#The materials that should not have gear melting recipes added.
	gearToMoltenMaterialBlacklist = []
	#The materials that should not have coin melting recipes added.
	coinToMoltenMaterialBlacklist = []
	#The materials that should not have rod melting recipes added.
	rodToMoltenMaterialBlacklist = []
	#The materials that should not have wire melting recipes added.
	wireToMoltenMaterialBlacklist = []
	#The materials that should not have ingot casting recipes added.
	toMaterialMaterialBlacklist = []
	#The materials that should not have storage block casting recipes added.
	toStorageBlockMaterialBlacklist = []
	#The materials that should not have nugget casting recipes added.
	toNuggetMaterialBlacklist = []
	#The materials that should not have plate casting recipes added.
	toPlateMaterialBlacklist = []
	#The materials that should not have gear casting recipes added.
	toGearMaterialBlacklist = []
	#The materials that should not have rod casting recipes added.
	toRodMaterialBlacklist = []

