
[celesteconfig]

	[celesteconfig.moon]
		#Celestial Configuration
		#Moon Width Scalar
		#Range: 0.0 ~ 100.0
		width = 2
		#Moon Height Scalar
		#Range: 0.0 ~ 100.0
		height = 2

	[celesteconfig.sun]
		#Sun Width Scalar
		#Range: 0.0 ~ 100.0
		width = 2
		#Moon Height Scalar
		#Range: 0.0 ~ 100.0
		height = 2

