#.
#Disables the migration of placed copycats from old versions to new ones. Setting this to true may cause copycats to lose their textures when you upgrade this mod. Restart the game to apply changes.
disableMigration = false

#.
#Enable/disable features. Values on server override clients
[features]
	#.
	copycat_stacked_half_layer = false
	copycat_vertical_stairs = false
	copycat_byte = true
	copycat_vertical_slice = true
	copycat_wooden_pressure_plate = false
	copycat_block = false
	copycat_shaft = true
	copycat_large_cogwheel = true
	copycat_fence = false
	copycat_wall = false
	copycat_cogwheel = true
	copycat_vertical_step = false
	copycat_sliding_door = true
	copycat_folding_door = true
	copycat_slope_layer = true
	copycat_light_weighted_pressure_plate = false
	copycat_stairs = false
	copycat_fence_gate = false
	copycat_slab = false
	copycat_board = true
	copycat_wooden_button = false
	copycat_trapdoor = false
	copycat_stone_pressure_plate = false
	copycat_pane = true
	copycat_half_panel = false
	copycat_slice = true
	copycat_beam = true
	copycat_door = true
	copycat_iron_door = true
	copycat_byte_panel = true
	copycat_corner_slice = true
	copycat_flat_pane = true
	copycat_ghost_block = false
	copycat_fluid_pipe = true
	copycat_heavy_weighted_pressure_plate = false
	copycat_iron_trapdoor = false
	copycat_half_layer = false
	copycat_stone_button = false
	copycat_ladder = false
	copycat_layer = true
	copycat_slope = false
	copycat_vertical_slope = false
	copycat_vertical_half_layer = false

#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#.
	#All copycats with a sloped surface
	slopes = true
	#.
	#All copycats that support multiple materials in a single block
	multistates = true
	#.
	#All copycats that can be resized by putting in more of the same copycat
	stackables = true
	#.
	#All copycats that can emit a redstone signal
	redstone = true
	#.
	#All copycats with extra functions/interactions
	functional = true
	#.
	#All copycats mimicking blocks from Create
	create = true

