#Dynamic light toggle
dynamic_light_toggle = true
#Light level an entity should emit when dynamic lights are on
#Example entry: minecraft:blaze=15
entity_lights = []
#Light level an item should emit when held when dynamic lights are on
#Example entry: minecraft:stick=15
item_lights = ["hexerei:moon_dust=8"]

["List of Extra Fonts"]
	#list of fonts that can be used, mainly for the book of shadows
	font_list = ["minecraft:default", "hexerei:fancy", "hexerei:bloody", "hexerei:earth", "hexerei:seattle", "hexerei:medieval", "hexerei:augusta"]

